### PR TITLE
Cherepnin Oleh: homework for lecture 15

### PR DESCRIPTION
**Pull request by Oleghon**

### CODE REVIEW

**Review by ogorbov — COMMENTED** [review]
1. CommonPasswordChecker should be mocked for PasswordValidatorTest
2. assertAll is good when you have many assertations related to 1 test case. checkPasswordTest (and other tests) covers multiple cases for one method. If you want to keep concise tests please use Parametrized test or split on multiple tests.

**Comment by Oleghon** [comment]
Done it.
Check out, please.

**Comment by ogorbov** [comment]
2 more tiny comments:
Please add a happy scenario. What password can be treated as valid? =) 
Please add tests for CommonPasswordChecker

**Comment by Oleghon** [comment]
Oh. Did not see `~`
My bad )
I fixed it.
Can you review that again)

**Review by ogorbov — APPROVED** [review]

**Pull request merged**
