### PR TITLE
Move files to terminal folder

### PR DESCRIPTION
**Pull request by olnikiforov**

### CODE REVIEW

**Comment by sae3023** [comment]
This PR only deletes the files. Are they already in a respective directory?

**Comment by olnikiforov** [comment]
Most likely git shows this way, because after i writee the command "git add" it showed me that 5 files were deleted and a new folder was created

**Comment by sae3023** [comment]
> Most likely git shows this way, because after i writee the command "git add" it showed me that 5 files were deleted and a new folder was created

We don't need an empty folder, we need a folder with your tasks. Please move the files to a directory corresponding to your name.

**Comment by olnikiforov** [comment]
I made ctrl+X folder with homework to terminal folder. on remote it shows correctly

**Review by sae3023 — APPROVED** [review]

**Pull request merged**
